/*
 * Dezentrale Members Administration
 * An API and application to administer the members of the hackspace dezentrale in Leipzig.
 *
 * The version of the OpenAPI document: 0.1.0-SNAPSHOT
 * Contact: p1ng0ut@mailbox.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package space.dezentrale.members.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.Generated;
import java.util.Objects;

/**
 * Error
 */
@JsonPropertyOrder({
  Error.JSON_PROPERTY_STATUS,
  Error.JSON_PROPERTY_TITLE,
  Error.JSON_PROPERTY_DESCRIPTION
})
@JsonTypeName("Error")
@Generated(value = "org.openapitools.codegen.languages.JavaMicronautServerCodegen", date = "2022-11-16T15:52:35.373+01:00[Europe/Berlin]")
@Introspected
public class Error {
    public static final String JSON_PROPERTY_STATUS = "status";
    private Integer status;

    public static final String JSON_PROPERTY_TITLE = "title";
    private String title;

    public static final String JSON_PROPERTY_DESCRIPTION = "description";
    private String description;

    public Error() {
    }

    public Error status(Integer status) {
        this.status = status;
        return this;
    }

    /**
     * The HTTP code which led to this error
     * @return status
     **/
    @Nullable
    @Schema(name = "status", description = "The HTTP code which led to this error", required = false)
    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getStatus() {
        return status;
    }

    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Error title(String title) {
        this.title = title;
        return this;
    }

    /**
     * A short title of the problem in kebab-case
     * @return title
     **/
    @Nullable
    @Schema(name = "title", example = "not-found", description = "A short title of the problem in kebab-case", required = false)
    @JsonProperty(JSON_PROPERTY_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getTitle() {
        return title;
    }

    @JsonProperty(JSON_PROPERTY_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTitle(String title) {
        this.title = title;
    }

    public Error description(String description) {
        this.description = description;
        return this;
    }

    /**
     * A description of the error and possible suggestions for solutions
     * @return description
     **/
    @Nullable
    @Schema(name = "description", example = "A member with the email you are looking for does not exist. Perhaps you have made a mistake?", description = "A description of the error and possible suggestions for solutions", required = false)
    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDescription() {
        return description;
    }

    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Error error = (Error) o;
        return Objects.equals(this.status, error.status) &&
            Objects.equals(this.title, error.title) &&
            Objects.equals(this.description, error.description);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, title, description);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Error {\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
