/*
 * Dezentrale Members Administration
 * An API and application to administer the members of the hackspace dezentrale in Leipzig.
 *
 * The version of the OpenAPI document: @project.version@
 * Contact: p1ng0ut@mailbox.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package space.dezentrale.members.model;

import java.util.Objects;
import java.util.Arrays;
import java.time.LocalDate;
import space.dezentrale.members.model.MemberRole;
import space.dezentrale.members.model.MemberStatus;
import space.dezentrale.members.model.MemberType;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Member
 */
@JsonPropertyOrder({
  Member.JSON_PROPERTY_NUMBER,
  Member.JSON_PROPERTY_ID,
  Member.JSON_PROPERTY_NICKNAME,
  Member.JSON_PROPERTY_EMAIL,
  Member.JSON_PROPERTY_DATE_OF_BIRTH,
  Member.JSON_PROPERTY_TYPE,
  Member.JSON_PROPERTY_ROLE,
  Member.JSON_PROPERTY_STATUS
})
@JsonTypeName("Member")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", date="2022-11-11T22:51:49.455628984+01:00[Europe/Berlin]")
@Introspected
public class Member {
    public static final String JSON_PROPERTY_NUMBER = "number";
    private Integer number;

    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_NICKNAME = "nickname";
    private String nickname;

    public static final String JSON_PROPERTY_EMAIL = "email";
    private String email;

    public static final String JSON_PROPERTY_DATE_OF_BIRTH = "dateOfBirth";
    private LocalDate dateOfBirth;

    public static final String JSON_PROPERTY_TYPE = "type";
    private MemberType type;

    public static final String JSON_PROPERTY_ROLE = "role";
    private MemberRole role;

    public static final String JSON_PROPERTY_STATUS = "status";
    private MemberStatus status;

    public Member(String nickname, String email) {
        this.nickname = nickname;
        this.email = email;
    }

    public Member number(Integer number) {
        this.number = number;
        return this;
    }

    /**
     * The member number, which (in the past) was and is simply incremented.
     * minimum: 1
     * @return number
     **/
    @Nullable
    @Min(1)
    @Schema(name = "number", example = "1", description = "The member number, which (in the past) was and is simply incremented.", required = false)
    @JsonProperty(JSON_PROPERTY_NUMBER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getNumber() {
        return number;
    }

    @JsonProperty(JSON_PROPERTY_NUMBER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNumber(Integer number) {
        this.number = number;
    }

    public Member id(String id) {
        this.id = id;
        return this;
    }

    /**
     * The UUID to identify the member in various processes.
     * @return id
     **/
    @Nullable
    @Pattern(regexp="^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$")
    @Schema(name = "id", example = "f2012985-fc7a-4500-a689-bf7637bebcfe", description = "The UUID to identify the member in various processes.", required = false)
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(String id) {
        this.id = id;
    }

    public Member nickname(String nickname) {
        this.nickname = nickname;
        return this;
    }

    /**
     * Get nickname
     * @return nickname
     **/
    @NotNull
    @Schema(name = "nickname", example = "wau", required = true)
    @JsonProperty(JSON_PROPERTY_NICKNAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getNickname() {
        return nickname;
    }

    @JsonProperty(JSON_PROPERTY_NICKNAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Member email(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get email
     * @return email
     **/
    @NotNull
    @Pattern(regexp="(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])")
    @Schema(name = "email", example = "wau.holland@ccc.de", required = true)
    @JsonProperty(JSON_PROPERTY_EMAIL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getEmail() {
        return email;
    }

    @JsonProperty(JSON_PROPERTY_EMAIL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setEmail(String email) {
        this.email = email;
    }

    public Member dateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
        return this;
    }

    /**
     * Get dateOfBirth
     * @return dateOfBirth
     **/
    @Nullable
    @Schema(name = "dateOfBirth", example = "Thu Dec 20 01:00:00 CET 1951", required = false)
    @JsonProperty(JSON_PROPERTY_DATE_OF_BIRTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    @JsonProperty(JSON_PROPERTY_DATE_OF_BIRTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Member type(MemberType type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * @return type
     **/
    @Nullable
    @Schema(name = "type", required = false)
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public MemberType getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(MemberType type) {
        this.type = type;
    }

    public Member role(MemberRole role) {
        this.role = role;
        return this;
    }

    /**
     * Get role
     * @return role
     **/
    @Nullable
    @Schema(name = "role", required = false)
    @JsonProperty(JSON_PROPERTY_ROLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public MemberRole getRole() {
        return role;
    }

    @JsonProperty(JSON_PROPERTY_ROLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRole(MemberRole role) {
        this.role = role;
    }

    public Member status(MemberStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * @return status
     **/
    @Nullable
    @Schema(name = "status", required = false)
    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public MemberStatus getStatus() {
        return status;
    }

    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStatus(MemberStatus status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Member member = (Member) o;
        return Objects.equals(this.number, member.number) &&
            Objects.equals(this.id, member.id) &&
            Objects.equals(this.nickname, member.nickname) &&
            Objects.equals(this.email, member.email) &&
            Objects.equals(this.dateOfBirth, member.dateOfBirth) &&
            Objects.equals(this.type, member.type) &&
            Objects.equals(this.role, member.role) &&
            Objects.equals(this.status, member.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(number, id, nickname, email, dateOfBirth, type, role, status);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Member {\n");
        sb.append("    number: ").append(toIndentedString(number)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    role: ").append(toIndentedString(role)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
