/*
 * Dezentrale Members Administration
 * An API and application to administer the members of the hackspace dezentrale in Leipzig.
 *
 * The version of the OpenAPI document: 0.1.0-SNAPSHOT
 * Contact: p1ng0ut@mailbox.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package space.dezentrale.members.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.Generated;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.time.LocalDate;
import java.util.Objects;

/**
 * Member
 */
@JsonPropertyOrder({
    Member.JSON_PROPERTY_NUMBER,
    Member.JSON_PROPERTY_ID,
    Member.JSON_PROPERTY_NICKNAME,
    Member.JSON_PROPERTY_EMAIL,
    Member.JSON_PROPERTY_DATE_OF_BIRTH,
    Member.JSON_PROPERTY_PGP_KEY,
    Member.JSON_PROPERTY_TYPE,
    Member.JSON_PROPERTY_ROLE,
    Member.JSON_PROPERTY_STATUS
})
@JsonTypeName("Member")
@Generated(value = "org.openapitools.codegen.languages.JavaMicronautServerCodegen", date = "2022-11-16T15:52:35.373+01:00[Europe/Berlin]")
@Introspected
public class Member {
    public static final String JSON_PROPERTY_NUMBER = "number";
    private Integer number;

    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_NICKNAME = "nickname";
    private String nickname;

    public static final String JSON_PROPERTY_EMAIL = "email";
    private String email;

    public static final String JSON_PROPERTY_DATE_OF_BIRTH = "dateOfBirth";
    private LocalDate dateOfBirth;

    public static final String JSON_PROPERTY_PGP_KEY = "pgpKey";
    private String pgpKey;

    public static final String JSON_PROPERTY_TYPE = "type";
    private MemberType type;

    public static final String JSON_PROPERTY_ROLE = "role";
    private MemberRole role;

    public static final String JSON_PROPERTY_STATUS = "status";
    private MemberStatus status;

    public Member(String nickname, String email) {
        this.nickname = nickname;
        this.email = email;
    }

    public Member number(Integer number) {
        this.number = number;
        return this;
    }

    /**
     * The member number, which (in the past) was and is simply incremented.
     * minimum: 1
     * @return number
     **/
    @Nullable
    @Min(1)
    @Schema(name = "number", example = "1", description = "The member number, which (in the past) was and is simply incremented.", required = false)
    @JsonProperty(JSON_PROPERTY_NUMBER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getNumber() {
        return number;
    }

    @JsonProperty(JSON_PROPERTY_NUMBER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNumber(Integer number) {
        this.number = number;
    }

    public Member id(String id) {
        this.id = id;
        return this;
    }

    /**
     * The UUID to identify the member in various processes.
     * @return id
     **/
    @Nullable
    @Pattern(regexp="^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$")
    @Schema(name = "id", example = "f2012985-fc7a-4500-a689-bf7637bebcfe", description = "The UUID to identify the member in various processes.", required = false)
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(String id) {
        this.id = id;
    }

    public Member nickname(String nickname) {
        this.nickname = nickname;
        return this;
    }

    /**
     * Get nickname
     * @return nickname
     **/
    @NotNull
    @Schema(name = "nickname", example = "wau", required = true)
    @JsonProperty(JSON_PROPERTY_NICKNAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getNickname() {
        return nickname;
    }

    @JsonProperty(JSON_PROPERTY_NICKNAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Member email(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get email
     * @return email
     **/
    @NotNull
    @Pattern(regexp="(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])")
    @Schema(name = "email", example = "wau.holland@ccc.de", required = true)
    @JsonProperty(JSON_PROPERTY_EMAIL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getEmail() {
        return email;
    }

    @JsonProperty(JSON_PROPERTY_EMAIL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setEmail(String email) {
        this.email = email;
    }

    public Member dateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
        return this;
    }

    /**
     * Get dateOfBirth
     * @return dateOfBirth
     **/
    @Nullable
    @Schema(name = "dateOfBirth", example = "Thu Dec 20 01:00:00 CET 1951", required = false)
    @JsonProperty(JSON_PROPERTY_DATE_OF_BIRTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    @JsonProperty(JSON_PROPERTY_DATE_OF_BIRTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Member pgpKey(String pgpKey) {
        this.pgpKey = pgpKey;
        return this;
    }

    /**
     * Get pgpKey
     *
     * @return pgpKey
     **/
    @Nullable
    @Schema(name = "pgpKey", example = "-----BEGIN PGP SIGNATURE----- iQIzBAABCAAdFiEEqcXfTSLpmZjZh1pREMAcWi9gWecFAmLP1OIACgkQEMAcWi9g WefaaRAA8OO6+VR30iCtEygf3HoIn85CBBYDjskWr+XNQ81dGVJjyTTl+MsRS+AY KV2aNn3ID9uufQGj6Jzf82EYHb401EZU0CH1gkQzAp5PN5bzwpbFwJhbuluJToaB Q7Kg94SQEsjwNkEEw6INZr/OQT+HW1YiuNKIhLncf/ErHMq8EqT3lkHxjQYRb6mt hpyP4/4esXNXOKVDxfThGXZFXZ8m9JQff5hglEYzz8+tnkc/XyxwNd7tqc1/FbKE U+84kVyPEHcUG5OMqN000CNpQmjfOTcUbdN44lYAL5WGe1Z7qTg4jf66LqmOoP9R ePzP3DsV5rBnKkSdoxryfBjvUW/4E5KlBMfgtHlGgVGQv/H0qbgBpHJEB08M4xGh GnSovlh8KFMSBaQHEaqux9Bv5yAQjmd5X5u+sES9uDETRuQ0wmcdXhOoFZW4NtiM jiq6wH+nhXa9oLV4G7simuCNpEtT038CCzUpla1tlnnxthimBE73uxy40z3cjtPw uoKropdjqgiKy4YCckKpA+hAY+/4pMRQ+V+ZgMqZmnU6Exkf1lJNwsJd2FK0u+Hu ZULkFS2Y2QFvATd+0dNNLvK+itYUaYdemOuYmjV0gbIvFzR9cqRNN6W0Dc0bpE+U kK+tiYuLhmpiRxwVkTgOZiaIjmWFLx1YrOSN7O2P3BFymq5QVNA= =tjq+ -----END PGP SIGNATURE-----", required = false)
    @JsonProperty(JSON_PROPERTY_PGP_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getPgpKey() {
        return pgpKey;
    }

    @JsonProperty(JSON_PROPERTY_PGP_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPgpKey(String pgpKey) {
        this.pgpKey = pgpKey;
    }

    public Member type(MemberType type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @Nullable
    @Schema(name = "type", required = false)
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public MemberType getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(MemberType type) {
        this.type = type;
    }

    public Member role(MemberRole role) {
        this.role = role;
        return this;
    }

    /**
     * Get role
     * @return role
     **/
    @Nullable
    @Schema(name = "role", required = false)
    @JsonProperty(JSON_PROPERTY_ROLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public MemberRole getRole() {
        return role;
    }

    @JsonProperty(JSON_PROPERTY_ROLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRole(MemberRole role) {
        this.role = role;
    }

    public Member status(MemberStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * @return status
     **/
    @Nullable
    @Schema(name = "status", required = false)
    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public MemberStatus getStatus() {
        return status;
    }

    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStatus(MemberStatus status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Member member = (Member) o;
        return Objects.equals(this.number, member.number) &&
            Objects.equals(this.id, member.id) &&
            Objects.equals(this.nickname, member.nickname) &&
            Objects.equals(this.email, member.email) &&
            Objects.equals(this.dateOfBirth, member.dateOfBirth) &&
            Objects.equals(this.pgpKey, member.pgpKey) &&
            Objects.equals(this.type, member.type) &&
            Objects.equals(this.role, member.role) &&
            Objects.equals(this.status, member.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(number, id, nickname, email, dateOfBirth, pgpKey, type, role, status);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Member {\n");
        sb.append("    number: ").append(toIndentedString(number)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
        sb.append("    pgpKey: ").append(toIndentedString(pgpKey)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    role: ").append(toIndentedString(role)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
